### ISSUE TITLE
midi percussive long error

### ISSUE THREAD

**Issue by 3hz** [SeanArchibald/scale-workshop#81] opened 2020-01-16 21:00 UTC
does anyone else find that when you switch amplitude envelope to percussive long that the midi function disables itself and you have to refresh the webpage to get the midi to work again?

**Comment by meszaros-lajos-gyorgy** [comment] 2020-01-23 14:30
As stated in the other ticket, can you give more information of the software and hardver you are using? If you could create a screenshot of the console messages when this occurs, then that would be the best.

**Comment by dxinteractive** [comment] 2021-07-08 05:57
I hit this one frequently. I'll record a video. It occurs on latest chrome, OSX catalina, and on latest ubuntu latest chrome. It is reproducible every time I use percussive long, but sometimes lasts quite a while. When it stops a "click" sound occurs, and no more sound is produced. Often after refreshing it'll almost immediately stop again despite no more notes being pressed, or last a shorter amount of time to previous.

(love scale workshop btw)

**Comment by dxinteractive** [comment] 2021-07-08 06:06
![image](https://user-images.githubusercontent.com/345320/124870674-727aad00-e006-11eb-84a3-ef3df699ea7c.png)

The error

**Comment by dxinteractive** [comment] 2021-07-08 06:17
Apologies for the mov file. Video helps show how it happens. You dont need to play very aggressively for it to occur.

Uploading scaleworkshopbug_small.mov…

**Comment by dxinteractive** [comment] 2021-07-08 06:26
Seems to be the same thing as #120 and #122

**Comment by SeanArchibald** [comment] 2021-10-04 11:24
Will be fixed in next version. See #126

**Closed by SeanArchibald** 2021-10-04 11:24 UTC
Labels: need more info, Web MIDI API
