### ISSUE TITLE
.tun Files Not working on Serum for specific EDO (above 12)

### ISSUE THREAD

**Issue by Aryaman-J** [SeanArchibald/scale-workshop#117] opened 2021-01-13 11:50 UTC
So I discovered Scale Workshop and have been having a lot of fun with it. I only have Serum which can import the .tun files. edos like 5edo, 10edo and 11edo seem to be working really well. Even just intonation .tun files seem to work. However, 15, 19, 22 and 31edo just won't work and the piano roll reverts back to 12edo. Weirdly enough, 24edo works just fine. I have been using the same method to export the tun files for all the edos mentioned. Does anyone know what could be wrong? Thank you so much!

**Comment by Aryaman-J** [comment] 2021-01-13 12:09
Okay, I found an interesting solution to this, and this was thanks to a thread before about someone using .tun files with serum. 
They had put the .tun tile in a comment and I copy pasted that and it ended up running 31-edo. Yet, scaleworkshop's exported 31edo didn't work.
When you open the .tun file in a text editor, the 4th line which says
_; https://sevish.com/scaleworkshop/?name=19%20equal%20divisions%20of%202%2F1&data=63.1578947368421%0A126.3157894736842%0A189.4736842105263%0A252.6315789473684%0A315.7894736842105%0A378.9473684210526%0A442.10526315789474%0A505.2631578947368%0A568.421052631579%0A631.578947368421%0A694.7368421052631%0A757.8947368421052%0A821.0526315789473%0A884.2105263157895%0A947.3684210526316%0A1010.5263157894736%0A1073.6842105263158%0A1136.842105263158%0A1200.&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ_
seems to be causing the problem.
As soon as I removed that the tun tiles start working. 
I find that especially weird because that doesn't explain why 5edo still works. Either way, just thought I could report this bug since this thread is now more relevant to potential problems with scale workshop.
Thanks sevish! You're the best.

**Comment by SeanArchibald** [comment] 2021-09-12 13:12
Looks like Serum has a problem handling comment lines that are long. But there's a reason we add that comment - it allows the user to get back to their original scale. Otherwise, the tun file contains a list of frequencies without any context. As far as I can tell the fix needs to come from Serum's side.

**Comment by SeanArchibald** [comment] 2021-09-25 14:41
I have reached out to Xfer support today to explain the situation and ask if they can investigate

**Comment by SeanArchibald** [comment] 2021-09-26 17:38
Something I just found out... Tun v1 did indeed have a 255 character limit for each line. The tun v1.5 library, which Serum uses, may do funny things if a line is any longer. While the nice folks at Xfer might increase this limit in the future, I'll keep this issue open while I figure out a smart way of staying within the 255 character limit while also allowing users a way to get their original scale data back (url or otherwise).

**Comment by SeanArchibald** [comment] 2021-09-26 22:49
Hi @Aryaman-J, there is a fix ready for testing on the development version (link below):
https://sevish.com/scaleworkshop-dev/

Are you still able to replicate the issue there? Please let me know your findings.

If it's working as you'd expect, this fix will be released in the Scale Workshop 1.4.

**Comment by SeanArchibald** [comment] 2021-10-04 09:30
Another user confirmed this fix worked - and 1.4 is now released. Going to close this issue but feel free to open a new one if there's still any problem

**Closed by SeanArchibald** 2021-10-04 09:30 UTC
